name: sync-to-miro

on:
  push:
    paths:
      - "**/*.yml"
      - "**/*.yaml"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install libraries
        run: pip install requests PyYAML

      - name: Send to Miro
        env:
          MIRO_TOKEN: ${{ secrets.MIRO_TOKEN }}
          MIRO_BOARD: ${{ secrets.MIRO_BOARD }}
        run: |
          python <<'PY'
          import os, yaml, glob, requests

          token  = os.environ['MIRO_TOKEN']
          board  = os.environ['MIRO_BOARD']
          hdr    = {'Authorization': f'Bearer {token}'}

          colors = [
              'light_yellow', 'yellow',
              'light_green',  'green',
              'light_blue',   'blue',
              'light_pink',   'pink'
          ]

          x = 0
          for idx, file in enumerate(sorted(glob.glob("*.yaml"))):
              y = 0
              for item in yaml.safe_load(open(file)):
                  content = item.get('text') or item.get('label') or None
                  if not content:
                      continue  # contentが無いデータはスキップ

                  r = requests.post(
                      f"https://api.miro.com/v2/boards/{board}/sticky_notes",
                      headers=hdr,
                      json={
                        "data": {"content": content},
                        "style": {"fillColor": colors[idx % len(colors)]},
                        "position": {"origin": "center", "x": x, "y": y}
                      }
                  )
                  print("Response", r.status_code, r.text[:100])
                  y += 120
              x += 300
          PY
